on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.4.7
        with:
          source: assets/sass/main.scss
          destination: style.css

      - name: 📂 Sync files TuSacTruyen
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: 103.200.23.120
          username: dasactruyen@dasactruyen.xyz
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /wp-content/themes/commicpro/
